### ISSUE TITLE
Ruby client and OneDrive

### ISSUE THREAD

**Issue by SeniorCompagnieTech** [microsoftgraph/msgraph-sdk-ruby#14]
Hey, I'd like to convert  `get 'https://graph.microsoft.com/v1.0/me/drive/sharedWithMe'` using this gem. 

It doesn't look like it has been implemented, am I wrong ?

**Comment by cbales** [comment]
You are correct. The library is lagging behind the API. This functionality is not currently in the metadata we provide.
As a workaround, you can modify the file [metadata.xml](https://github.com/microsoftgraph/msgraph-sdk-ruby/blob/master/data/metadata_v1.0.xml) and add the following data as a child node of the Schema element:

 ```
<Function Name="sharedWithMe" IsBound="true">
    <Parameter Name="bindingParameter" Type="microsoft.graph.drive"/>
    <ReturnType Type="Collection(microsoft.graph.driveItem)"/>
</Function>
```

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
