### ISSUE TITLE
Delete Subscription - 500 ExtensionError

### ISSUE THREAD

**Issue by loganh0522** [microsoftgraph/msgraph-sdk-ruby#15]
When I try to delete a subscription I get this error. Any reasons why this might be happening? 

    def self.delete_subscription(user)   
      if user.outlook_token.expired?
        user.outlook_token.refresh!(user)
      end
      
      callback = Proc.new do |r| 
        r.headers['Authorization'] = "Bearer #{user.outlook_token.access_token}"
        r.headers['Content-type'] = 'application/json'
        r.headers['X-AnchorMailbox'] = user.email
      end

      graph = MicrosoftGraph.new(base_url: 'https://graph.microsoft.com/v1.0/',
                                cached_metadata_

      graph.service.delete("subscriptions/#{subscriptionId}") 

500 ExtensionError: "Operation: Delete; Exception: [There was no raw user ticket in the requestPropertyMappings]" from "https://graph.microsoft.com/v1.0/subscriptions/{subscriptionID}"

**Comment by cbales** [comment]
If you're getting a 500 error, I'm wondering if this is a Graph error and not SDK-related. Could you post the raw request/response of this call? Otherwise, you should try asking on StackOverflow with the tag [microsoft-graph], where someone from the webhooks team should be able to help you.

**Comment by loganh0522** [comment]
@cbales I realized my problem was that I was trying to delete using /v1.0/' and not /beta/. Subscriptions in graph v1.0 currently does not work, so I have to use Beta to create/update/destroy a subscription. Also just so you know, for when you guys do some updates, this gem currently has base_url: 'https://graph.microsoft.com/v1.0/' hardcoded into the gem. i had to change this to allow myself to choose to use beta or v1.0.

**Comment by loganh0522** [comment]
@cbales - Next time I find an issue, that I am able to find a fix for I will reference it like you did above!!

**Comment by cbales** [comment]
Thanks for following up with your solution!
