### ISSUE TITLE
MicrosoftGraph::Models::ODataErrorsODataError when trying to fetch the list of messages

### ISSUE THREAD

**Issue by andreimerfu** [microsoftgraph/msgraph-sdk-ruby#156]
Context: I'm trying to access the list of messages using the `me.messages` method. However, every time the following exception is raised without any other error message.

Any thoughts about how I can debug this? Thank you!

```ruby
client.me.messages.get.resume
MicrosoftGraph::Models::ODataErrorsODataError: MicrosoftGraph::Models::ODataErrorsODataError
```

**Comment by baywet** [comment]
Hi @andreimerfu 
Thanks for trying the Ruby SDK and for reaching out.
This object should have an error property and under it a message property with a detailed explanation.
Let us know if you need anything else.

**Comment by andreimerfu** [comment]
Ok, I rescue the exception and I found the error message. Thank you!
