### ISSUE TITLE
Graph path & version is hardcoded in MicrosoftGraph

### ISSUE THREAD

**Issue by caitlinrussell** [microsoftgraph/msgraph-sdk-ruby#16]
https://github.com/microsoftgraph/msgraph-sdk-ruby/blob/8305fdf7a79c513229fa06c5da46e05c9977ea47/lib/microsoft_graph.rb#L13

Reported by @loganh0522 in #15

**Comment by danilobarion1986** [comment]
Hi! I want to open a Pull Request for this issue, but I I could not fork the repository... Is there some permission issue or it's a GitHub temporary error?

**Comment by darrelmiller** [comment]
@danilobarion1986 There should be no issue forking the repo.  GitHub were having service issues last night so that may be the reason you had problems forking.

**Comment by danilobarion1986** [comment]
> Hi! I want to open a Pull Request for this issue, but I I could not fork the repository... Is there some permission issue or it's a GitHub temporary error?

Forget it, I forked it now!
