### ISSUE TITLE
gem install microsoft_graph takes a long time

### ISSUE THREAD

**Issue by mhais22** [microsoftgraph/msgraph-sdk-ruby#166]
When I try installing this gem it takes a long time (a few minutes) is this expected? It is specifically getting stuck here:

```
Parsing documentation for microsoft_graph_core-0.3.1
Installing ri documentation for microsoft_graph_core-0.3.1
Parsing documentation for microsoft_graph-0.22.1
```

**Comment by baywet** [comment]
Hi @mhais22 
Thanks for using the SDK and for reaching out.
I'm going to close as duplicate of #144 to keep a centralized discussion as the cause is essentially the same here. (as well as workarounds for the time being).
