### ISSUE TITLE
Webhooks suddenly stopped sending Data

### ISSUE THREAD

**Issue by loganh0522** [microsoftgraph/msgraph-sdk-ruby#17]
This is probably an issue with the Webhooks module, and I asked a stackoverflow question as @cbales recommended, but I just wanted to clarify that it is a webhook issue. if it it I will close this issue. 

What happened was my app was receiving and processing WebHook notifications just fine, and then suddenly I stopped receiving notifications from the WebHook. I am just wondering what might have caused this.

As always, I appreciate the help.

**Comment by dpim** [comment]
Thanks for reporting this issue. I've brought this to the attention of the team working on Graph webhooks.

**Comment by cbales** [comment]
Please reopen if you find this to be an SDK issue and not a service issue.
