### ISSUE TITLE
Downloading profile photos

### ISSUE THREAD

**Issue by basicsandwich** [microsoftgraph/msgraph-sdk-ruby#19]
Per the [Get Profile Photo docs](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/profilephoto_get), it appears that getting photo meta data is supported by the SDK:

e.g. `graph.me.photo` => GET /me/photo

But that getting the actual image is not supported.  GET /me/photo/$value.  Am I missing something, or is this a known issue?.  Thanks!

**Comment by dpim** [comment]
I believe this is a known issue. You may have to fall back to REST in order to get ~/photo/$ref.

**Comment by fribeiro1** [comment]
You may also want to add support for uploading photos.

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
