### ISSUE TITLE
Can't find documentation for fetching

### ISSUE THREAD

**Issue by amitleshed** [microsoftgraph/msgraph-sdk-ruby#205]
Where can I find the docs for simple client api calls like such as:

```
    response = @client.me.calendar_view.get(
      query_parameters: {
        'startDateTime' => start_time,
        'endDateTime' => end_time,
        '$orderby' => 'start/dateTime'
      }
    )
```

The code I provided doesn't work, as it accepts a method "headers" so I assume I'm missing a usage of some class.

Here's how I initialized the client

```
context = MicrosoftKiotaAuthenticationOAuth::ClientCredentialContext.new(
      TENANT_ID, CLIENT_ID, CLIENT_SECRET
    )

    @authentication_provider = MicrosoftGraphCore::Authentication::OAuthAuthenticationProvider.new(
      context, nil, SCOPES
    )

    adapter = MicrosoftGraph::GraphRequestAdapter.new(@authentication_provider)
    @client = MicrosoftGraph::GraphServiceClient.new(adapter) 
```

All I really need is the ruby-sdk method documentation/examples which I can't find. Just found the rubyonrails example app but it doesn't use the sdk, only uses straight http calls to microsoft-graph.

Thanks.

**Comment by baywet** [comment]
Hi @amitleshed 
Thank you for using the Ruby SDK and for reaching out

Have you tried something like this?

```ruby
response = @client.me.calendar_view.get({
      query_parameters: CalendarViewRequestBuilderGetQueryParameters.new {
        'startDateTime' => start_time,
        'endDateTime' => end_time,
        '$orderby' => 'start/dateTime'
      }
    })
```

**Comment by amitleshed** [comment]
Hey! thanks a lot, I have tried this, but still get a NoMethodError

`(undefined method 'headers' for {:query_parameters=>#<MicrosoftGraph::Me::Calendar::CalendarView::CalendarViewRequestBuilder::CalendarViewRequestBuilderGetQueryParameters:0x000000011cf745f0 @start_date_time=2024-05-12 00:00:00 -0400, @end_date_time=2024-05-19 00:00:00 -0400, @orderby="start/dateTime">}:Hash):`

Not sure what am I doing wrong. Are there any usage examples of the SDK?

**Comment by baywet** [comment]
ok, let's try this then

```ruby
response = @client.me.calendar_view.get(RequestConfiguration.new {
      query_parameters: CalendarViewRequestBuilderGetQueryParameters.new {
        start_date_time: start_time,
        end_date_time: end_time,
        orderby: 'start/dateTime'
      }
    })
```
Request configuration comes from [here](https://github.com/microsoft/kiota-abstractions-ruby/blob/2e8a00cfb9413782d98449e0419efe5098e1d107/lib/microsoft_kiota_abstractions/request_configuration.rb#L3)
