### ISSUE TITLE
Support to beta API

### ISSUE THREAD

**Issue by ricardopacheco** [microsoftgraph/msgraph-sdk-ruby#21]
This gem support beta version?

**Comment by cbales** [comment]
Currently, there are bugs that prevent the beta file from working correctly. If you want to try it out, you can set `cached_metadata_file` to https://graph.microsoft.com/beta/$metadata

**Comment by kamaradclimber** [comment]
I've tried using this as well, no luck so far. 
> undefined method `[]' for nil:NilClass
on beta function such as /me/findRooms

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
