### ISSUE TITLE
uninitialized constant MicrosoftGraphCore::Authentication (NameError)

### ISSUE THREAD

**Issue by GarrisonD** [microsoftgraph/msgraph-sdk-ruby#211]
Instead of `gem "microsoft_graph"` do `gem "microsoft_graph", "~> 0.22.2"`

Otherwise not the latest version could get installed and the snippets from README.md don't work.

**Comment by baywet** [comment]
Hi @GarrisonD 
Thanks for using the SDK and for reaching out.
I put together #215 to address this issue.
Let us know if there's anything else.
