### ISSUE TITLE
undefined method `users_by_id' for #<MicrosoftGraph::GraphServiceClient

### ISSUE THREAD

**Issue by GarrisonD** [microsoftgraph/msgraph-sdk-ruby#212]
I installed the SDK with `gem "microsoft_graph", "~> 0.22.2"` and just ran the snippets from the README.md:

```
result = client.users_by_id("<user-id>").get.resume
```

```
undefined method `users_by_id' for #<MicrosoftGraph::GraphServiceClient
```

**Comment by rift137** [comment]
I think that this is in reference to the README.md suggesting that to retrieve a user by their ID you should use:
`result = client.users_by_id("<user-id>").get.resume` which does not work as expected.

**Comment by baywet** [comment]
@rift137 thanks for pointing this out.
Is this something you'd like to submit a pull request for provided some guidance?
