### ISSUE TITLE
Microsoft Graph blocking all requests from AWS?

### ISSUE THREAD

**Issue by nneal** [microsoftgraph/msgraph-sdk-ruby#23]
The issue we are facing is quite unexpected, We use Microsoft Graph API Client for Ruby, https://github.com/microsoftgraph/msgraph-sdk-ruby but we were also able to reproduce it in postman and curl.

Any request sent to Microsoft Graph API from Europe and Brazil received a success response,
but requests sent from our production server (AWS, Oregon) always, always fail.

here is an example request:
```
curl -X GET   https://graph.microsoft.com/v1.0/users/a9f4a487353d5ca4/contacts/ 

-H 'Authorization: Bearer ACCESS_TOKEN'

-H 'Cache-Control: no-cache' 

-H 'Content-Type: application/x-www-form-urlencoded'  

-H 'Postman-Token: e3ba1d72-5b17-b0ca-692e-ecbc96110c93'  

-H 'SdkVersion: Graph-ruby-0.1.0'
```
 
and the answer we get on production (AWS, Oregon):
```
{

"error": {

    "code": "ErrorServiceUnavailable",

    "message": "Active Directory operation did not succeed. Try again later.",

    "innerError": {

      "request-id": "2ab9ab7a-eb21-494d-8970-69c5101b87da",

      "date": "2018-03-15T15:24:19"

    }

  }

}
```

Our API Keys are fresh, and access token is requested with offline access, and so is always refreshed.

Also the fact that API is working from Europe and Brazil and not from AWS Oregon,
gave us the impression that:

1) API calls are restricted from AWS
OR
2) Your CDN has some downtime issues

some more details nslookup graph.microsoft.com:

output from production (AWS Oregon, failed requests):

```
Server:         10.179.0.2
Address:        10.179.0.2#53

Non-authoritative answer:
graph.microsoft.com     canonical name = www.ags.graph.microsoft.com.akadns.net.
www.ags.graph.microsoft.com.akadns.net  canonical name = www.ags-prd.graph.microsoft.com.akadns.net.
www.ags-prd.graph.microsoft.com.akadns.net      canonical name = wus.ags-prd.graph.microsoft.com.akadns.net.
wus.ags-prd.graph.microsoft.com.akadns.net      canonical name = wus-a.ags-prd.graph.microsoft.com.akadns.net.
Name:   wus-a.ags-prd.graph.microsoft.com.akadns.net
Address: 137.135.50.212
Name:   wus-a.ags-prd.graph.microsoft.com.akadns.net
Address: 168.62.11.66
Name:   wus-a.ags-prd.graph.microsoft.com.akadns.net
Address: 168.62.16.21
Name:   wus-a.ags-prd.graph.microsoft.com.akadns.net
Address: 168.62.24.134


output from dev (Europe, successful requests):
Server:         192.168.0.1
Address:        192.168.0.1#53

Non-authoritative answer:
graph.microsoft.com     canonical name = www.ags.graph.microsoft.com.akadns.net.
www.ags.graph.microsoft.com.akadns.net  canonical name = www.ags-prd.graph.microsoft.com.akadns.net.
www.ags-prd.graph.microsoft.com.akadns.net      canonical name = weu.ags-prd.graph.microsoft.com.akadns.net.
weu.ags-prd.graph.microsoft.com.akadns.net      canonical name = weu-a.ags-prd.graph.microsoft.com.akadns.net.
Name:   weu-a.ags-prd.graph.microsoft.com.akadns.net
Address: 65.52.144.66
Name:   weu-a.ags-prd.graph.microsoft.com.akadns.net
Address: 213.199.132.167
Name:   weu-a.ags-prd.graph.microsoft.com.akadns.net
Address: 23.97.144.12
Name:   weu-a.ags-prd.graph.microsoft.com.akadns.net
Address: 65.52.136.185
```

**Comment by MIchaelMainer** [comment]
Strange. I'm looking into this and will respond.

**Comment by MIchaelMainer** [comment]
When did you start seeing this? Are you still seeing this?

**Comment by nneal** [comment]
We started seeing it on Wednesday (the first time we tried, I believe) and we were still seeing it earlier today. Thank you for investigating!

**Comment by nneal** [comment]
@MIchaelMainer We tried again with same exact queries / no other changes and it works now. I'd still be curious if you learned anything looking into this. Could be helpful for us in the future.

**Comment by mspanesar145** [comment]
I am trying the https://graph.microsoft.com/v1.0/me/events service but i am getting the below response.

{
    "error": {
        "code": "ErrorServiceUnavailable",
        "message": "Active Directory operation did not succeed. Try again later.",
        "innerError": {
            "request-id": "2dbea951-66d1-45d7-a0cb-9e16a47a8392",
            "date": "2018-06-19T18:43:09"
        }
    }
}

**Comment by MIchaelMainer** [comment]
@nneal I'm sorry that I didn't get back to you on this service issue. 

@mspanesar145 What is your request rate? Are requests timing out? I suspect that there may be a service issue that requires your client to progressively backoff your request rate.

**Comment by mspanesar145** [comment]
@MIchaelMainer I was trying using postman and curl. Right now there is no traffic hitting the API recursively. However request rate will be around 2 or 3 requests per minute. 
I checked there is no timeout. I am getting the response in 2 or 3 seconds.

**Comment by MIchaelMainer** [comment]
@mspanesar145 Are you still seeing the ErrorServiceUnavailable response?
825027

**Comment by MIchaelMainer** [comment]
Closing as I'm unsure whether this issue is still valid. Reopen if this issue is still valid.
