### ISSUE TITLE
How to remove group member?

### ISSUE THREAD

**Issue by isaiev** [microsoftgraph/msgraph-sdk-ruby#24]
I cat add group member through method ```<<```
But how can I remove group member?

**Comment by isaiev** [comment]
I was wrong, method ```<<``` not actually adds member on remote server, it only adds nested object.

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
