### ISSUE TITLE
Sending drafts through outlook with Rails

### ISSUE THREAD

**Issue by ZASMan** [microsoftgraph/msgraph-sdk-ruby#25]
Hi,

I'm wondering if this API can be used for something like opening Outlook and saving an email as a draft automatically in the Outlook drafts folder. Thank you!

**Comment by cbales** [comment]
The SDK can be used to programmatically access email, but does not manipulate the program itself. You can create new emails and save them as drafts according to the documentation here: [Outlook mail](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/mail_api_overview)

If you want to see a working sample of working with email, you can look at the REST sample for Ruby: [https://github.com/microsoftgraph/ruby-connect-rest-sample](https://github.com/microsoftgraph/ruby-connect-rest-sample)

**Comment by ZASMan** [comment]
Thank you for your prompt response! That should put me on the right track. Also, this looks like very solid sample app. Thanks!
