### ISSUE TITLE
Q: Is there the way set $select parameter?

### ISSUE THREAD

**Issue by andrzej-zuralovic** [microsoftgraph/msgraph-sdk-ruby#26]
Is there the way to set $select query parameter in this gem? https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters#select-parameter

**Comment by gnmonsalve** [comment]
It's probably too late, but someone else might have this doubt (like I did a few hours ago).
You can use:
https://github.com/microsoftgraph/msgraph-sdk-ruby/blob/4ee17fd74e729c362bb452f683c973d0a42af28f/lib/odata/service.rb#L27-L37

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
