### ISSUE TITLE
Hardcoded base_url

### ISSUE THREAD

**Issue by hasanen** [microsoftgraph/msgraph-sdk-ruby#28]
I wonder if `base_url` be read from options instead of using just`BASE_URL`? https://github.com/microsoftgraph/msgraph-sdk-ruby/blob/4ee17fd74e729c362bb452f683c973d0a42af28f/lib/microsoft_graph.rb#L19

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
