### ISSUE TITLE
Subscriptions aren't available

### ISSUE THREAD

**Issue by afkplus** [microsoftgraph/msgraph-sdk-ruby#32]
This may be an issue, or may not. Can't say for sure because of the lack of documentation. I am trying to subscribe to some calendar events, but couldn't figure out how to do that? I'll appreciate if anyone can guide me through this if it is available in this gem. https://developer.microsoft.com/en-us/graph/docs/concepts/webhooks

**Comment by MIchaelMainer** [comment]
This gem does not currently support that functionality. We'll need to update the client to support subscriptions.
