### ISSUE TITLE
Support for pulling more than 1000 items in a collection association

### ISSUE THREAD

**Issue by amitkoren** [microsoftgraph/msgraph-sdk-ruby#39]
CollectionAssociation has a hard limit of 1000 items 

```
def last?
   @loaded || @internal_values.size >= 1000
end
```

It would be useful to make this limit configurable and/or optional for applications that need to cache the entire collection of items (e.g., contacts).

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
