### ISSUE TITLE
Is this Gem still supported?

### ISSUE THREAD

**Issue by sk-** [microsoftgraph/msgraph-sdk-ruby#42]
This library has been more than 3 years in preview status, and despite al the user requests there have been no major changes.

**Comment by darrelmiller** [comment]
Hey @sk- We currently have no developers working on it.  Our backlog is full until after Build in May.  After that we are going to startup again on other languages such as Ruby.  Sorry for the delay, we are only a small team, so we have had to prioritize ruthlessly.

**Comment by KevinColemanInc** [comment]
@darrelmiller It is July. Whats going on?

**Comment by darrelmiller** [comment]
@KevinColemanInc We still have no developers available to work on this.  Let me review the PRs and see whether we can just act as middleman for community PRs.

**Comment by KevinColemanInc** [comment]
@darrelmiller 

It would be cool if you could at least publish `master` to rubygems. I am having to install `git` on production servers just so I can load this gem from github, since master has a few bug fixes.

**Comment by Samsinite** [comment]
@darrelmiller when do you think the PRs will get reviewed? If you guys aren't going to do anything to this gem, you might as well just give someone in the open source community the ability to maintain and contribute, while maintaining ownership.

**Comment by darrelmiller** [comment]
I have an environment setup to be able to build and depoy a new gem from master, however, when I try running the `bundle exec rspec` I am getting errors.  

![image](https://user-images.githubusercontent.com/447694/63311872-8790aa80-c2cd-11e9-8813-9dc1c5f46eda.png)

Can someone confirm if they are seeing this also, or is it my environment?  I'm running this in docker container built from this:

```
FROM ruby:2.4.0-alpine

RUN apk update && apk add nodejs build-base git libxml2-dev libxslt-dev
```

**Comment by darrelmiller** [comment]
Turns out bigdecimal is a gem and we were missing it as a dev dependency.  Unit tests are passing.

**Comment by KevinColemanInc** [comment]
It worked for me on macOS and rvm
<img width="932" alt="image" src="https://user-images.githubusercontent.com/2381771/63312642-03cbc380-c2b7-11e9-9b5c-263cd758e5ca.png">

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
