### ISSUE TITLE
Please release an update to ruby gems with the latest version

### ISSUE THREAD

**Issue by KevinColemanInc** [microsoftgraph/msgraph-sdk-ruby#49]
The last update to ruby gems is [0.1.3 (June 13, **2017**)](https://rubygems.org/gems/microsoft_graph). It seems that there have been [bugs since then](https://github.com/microsoftgraph/msgraph-sdk-ruby/issues/29) and it would be great if I didn't have to load the gem from Github.

**Comment by hasghari** [comment]
I came here to request the same thing.

**Comment by sujitpranavsunray** [comment]
Any updated version of this gem???

**Comment by Younnah** [comment]
Hi!
I request the same thing, thank you!

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
