### ISSUE TITLE
Getting ADAL::UserCredential::UnsupportedAccountTypeError

### ISSUE THREAD

**Issue by lemmycaution** [microsoftgraph/msgraph-sdk-ruby#5]
Hi there,

I'm always getting below error whenever I try to run examples, also in https://github.com/AzureAD/azure-activedirectory-library-for-ruby project.

```Unsupported account type for authentication: Unknown. (ADAL::UserCredential::UnsupportedAccountTypeError)```

Tried to set everything properly on https://manage.windowsazure.com and https://portal.azure.com both, but no luck :/

What I'm missing? Any help most appreciated. Thanks.

**Comment by cbales** [comment]
Hello! This is a great question for StackOverflow. Could you tag "microsoftgraph", "adal", and "ruby" in your question? Also, include some information about what type of authentication you are attempting and the setup in your code. This will ensure that others who have the same question can all see the answer. Thanks!
