### ISSUE TITLE
Emoji support: Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by KevinColemanInc** [microsoftgraph/msgraph-sdk-ruby#50]
I am trying to call `to_json` on a message with the subject and body having emojis (🎡✈️).

The following exception in thrown:
```
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8
```

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
