### ISSUE TITLE
`#filter` creates invalid queries; does not escape invalid characters

### ISSUE THREAD

**Issue by KevinColemanInc** [microsoftgraph/msgraph-sdk-ruby#53]
```ruby
graph.me.mail_folders.find(INBOX_NAME)
                     .messages
                     .filter(subject: "hello'")
```

If you search of an email with a subject containing a `'`, then it creates a query like `subject eq 'hello''`

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
