### ISSUE TITLE
How do you pull down the MIME type of an email?

### ISSUE THREAD

**Issue by KevinColemanInc** [microsoftgraph/msgraph-sdk-ruby#56]
I am not seeing how to do this:
https://docs.microsoft.com/en-us/graph/outlook-get-mime-message#get-mime-content-of-an-outlook-message

The `MicrosoftGraph::Message` class returned from `messages.find(..)` does not have a `value` attribute.

**Comment by ddyett** [comment]
ruby library is now archived.

**Comment by KevinColemanInc** [comment]
@dylank What is it replaced with?
