### ISSUE TITLE
Can't get organization contact as members

### ISSUE THREAD

**Issue by YamajiTomoya** [microsoftgraph/msgraph-sdk-ruby#58]
Hello.  I am in trouble.

I created distribution group in exchange online.
This DG(distribution group) includes organization contact as member.

I want to get all member email addresses of DG.
And I wrote the following code.

```
distriobution_group = graph.groups.find(~ID of DG ~)
members = distribution_group.members
members_email = members.map { |m| m.mail || m.user_principal_name }
```

But, the following error was output.
```
NoMethodError: undefined method `new' for nil:NilClass
from /vendor/bundle/ruby/2.6.0/gems/microsoft_graph0.1.3/lib/microsoft_graph/collection_association.rb:219:in `block in fetch_next_page' 
```

Is this a bug?
I would appreciate your help.

Thank you for reading my ugly English.

**Comment by MIchaelMainer** [comment]
Your English is fine, our response time is not, and for that, we apologize. I also apologize as we have not funded support for this client library. We are hopeful. 

At this, I'm unable to help on this issue.

**Comment by ddyett** [comment]
we're no longer supporting ruby
