### ISSUE TITLE
list endpoints return empty

### ISSUE THREAD

**Issue by mattduggan** [microsoftgraph/msgraph-sdk-ruby#60]
If I list calendars or mail_folders, I always get an empty result:
```rb
> graph.me.calendars
=> []
> graph.me.mail_folders
=> []
```
However, get calendar and finding a folder returns a result:
```rb
graph.me.calendar
=> {"id":"<CALENDAR_ID>","name":"Calendar","color":"auto","change_key":"<CHANGE_KEY>"}
graph.me.mail_folders.find('inbox')
=> {"id":"<FOLDER_ID>","display_name":"Inbox","parent_folder_id":"<PARENT_FOLDER_ID>","child_folder_count":0,"unread_item_count":0,"total_item_count":0}
```

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
