### ISSUE TITLE
How to create onlineMeetings?

### ISSUE THREAD

**Issue by aafaq-hassan-confiz** [microsoftgraph/msgraph-sdk-ruby#65]
Is it possible to create onlineMeetings, if yes, then how?

https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
