### ISSUE TITLE
Can't Create Instances Unless Using ADAL

### ISSUE THREAD

**Issue by fribeiro1** [microsoftgraph/msgraph-sdk-ruby#67]
If you don't use ADAL, you get the following error when creating a GraphSession instance:

Traceback (most recent call last):
        7: from /usr/bin/irb:11:in `<main>'
        6: from (irb):2
        5: from (irb):2:in `new'
        4: from /usr/local/share/gems/gems/microsoft_graph-0.1.3/lib/microsoft_graph.rb:16:in `initialize'
        3: from /usr/local/share/gems/gems/microsoft_graph-0.1.3/lib/microsoft_graph.rb:16:in `new'
        2: from /usr/local/share/gems/gems/microsoft_graph-0.1.3/lib/odata/service.rb:11:in `initialize'
        1: from /usr/local/share/gems/gems/microsoft_graph-0.1.3/lib/odata/service.rb:230:in `fetch_metadata'
NameError (uninitialized constant OData::Service::Net)

If you add "require 'net/http'' to your own code, you still get another error:

Traceback (most recent call last):
        7: from /usr/bin/irb:11:in `<main>'
        6: from (irb):4
        5: from (irb):4:in `new'
        4: from /usr/local/share/gems/gems/microsoft_graph-0.1.3/lib/microsoft_graph.rb:16:in `initialize'
        3: from /usr/local/share/gems/gems/microsoft_graph-0.1.3/lib/microsoft_graph.rb:16:in `new'
        2: from /usr/local/share/gems/gems/microsoft_graph-0.1.3/lib/odata/service.rb:11:in `initialize'
        1: from /usr/local/share/gems/gems/microsoft_graph-0.1.3/lib/odata/service.rb:235:in `fetch_metadata'
NameError (uninitialized constant Nokogiri)

You can workaround by also adding "'require 'nokogiri'" to your own code.

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
