### ISSUE TITLE
Can't Create Users Unless Using ADAL

### ISSUE THREAD

**Issue by fribeiro1** [microsoftgraph/msgraph-sdk-ruby#68]
If you don't use ADAL, you get the following error when creating an user:

Traceback (most recent call last):
        7: from /usr/bin/irb:11:in `<main>'
        6: from (irb):8
        5: from /usr/local/share/gems/gems/microsoft_graph-0.1.3/lib/microsoft_graph/collection_association.rb:136:in `create!'
        4: from /usr/local/share/gems/gems/microsoft_graph-0.1.3/lib/microsoft_graph/collection_association.rb:136:in `tap'
        3: from /usr/local/share/gems/gems/microsoft_graph-0.1.3/lib/microsoft_graph/collection_association.rb:136:in `block in create!'
        2: from /usr/local/share/gems/gems/microsoft_graph-0.1.3/lib/microsoft_graph/base_entity.rb:82:in `save!'
        1: from /usr/local/share/gems/gems/microsoft_graph-0.1.3/lib/microsoft_graph/base.rb:44:in `to_json'
NoMethodError (undefined method `to_json' for #<Hash:0x00005581b19d8a90>)

You can workaround it by adding "require 'json'" to your own code.

Similar to #67

**Comment by baywet** [comment]
Thanks for reporting this issue. That version of the SDK has been deprecated a number of years ago. We're now starting the work on a new generation of this SDK and you can learn all about it on the updated readme page.
