### ISSUE TITLE
Gem Load Error is: uninitialized constant MicrosoftGraph::Base

### ISSUE THREAD

**Issue by loganh0522** [microsoftgraph/msgraph-sdk-ruby#8]
I have developed and used the microsoft_graph gem in development without a hiccup. However, when I push the code to Heroku, I get an error saying Gem Load Error is: uninitialized constant MicrosoftGraph::Base. The backtrace for the gem load is below. 

Any help is much appreciated :)

**Comment by sushant12** [comment]
@loganh0522  did u find a solution? I am getting a similiar issue  

```
/home/nikesh/.rvm/gems/ruby-2.3.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'microsoft_graph'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant MicrosoftGraph::Collection

```
