### ISSUE TITLE
microsoft_graph_core 0.1.0 depends on broken version of microsoft_kiota_authentication_oauth (v0.5.0)

### ISSUE THREAD

**Issue by iris-lux-highspot** [microsoftgraph/msgraph-sdk-ruby#94]
I'm using microsoft_graph v0.12.0 which depends on microsoft_graph_core v0.1.0. microsoft_graph_core v0.1.0 depends on microsoft_kiota_authentication_oauth v0.5.0 which has a bug where the authentication provider fails to load because of a [typo in the code](https://github.com/microsoft/kiota-authentication-oauth-ruby/blob/53cf0e43267453a4d9dda16b0f2ff7247e3eeb3c/lib/microsoft_kiota_authentication_oauth/oauth_access_token_provider.rb#L32). 

I'm trying to initialize the kiota authentication provider but I can't because of the bug, and I can't update to the microsoft_kiota_authentication_oauth v0.6.0 (where the bug has been fixed) because of microsoft_graph_core's dependency on the earlier version.

Can you please update microsoft_graph_core v0.1.0 so that it depends on microsoft_kiota_authentication_oauth v0.6.0 or later?

**Comment by baywet** [comment]
Thanks for reporting this. And for your patience in the matter. This issue has been resolved in subsequent versions of the SDK, so updating to a newer version (0.19.0 at the time of writing) should resolved your issue.
